baseURL = "https://pfeister.dev/"
languageCode = "en-us"
title = "Paul Pfeister"
theme = "hello-friend-ng"
enableRobotsTXT = true

[params]
    defaultTheme = "dark"
    description = "Portfolio of Paul Pfeister"
    #homeSubtitle =  "Security researcher, open source developer, and technology consultant"
    keywords = "Security Researcher, Security Engineer, Software Engineer, Bug Bounty Hunter, Sherlock Project"
    enableThemeToggle = true
    #enableSharingButtons = true
    disableReadOtherPosts = true
    social = [
        { name = "github", url = "https://github.com/ppfeister" },
        { name = "linkedin", url = "https://www.linkedin.com/in/paulpfeister/" },
        { name = "telegram", url = "https://t.me/ppfeister" },
        { name = "keybase", url = "https://keybase.io/ppfeister" },
    ]
    author = "Paul Pfeister"

#[params.utterances]
#    repository = "ppfeister/pfeister.dev-utterances"
#    issueTerm = "pathname"
#    label = "utterances"
#    theme = "photon-dark"

[params.footer]
    #trademark = "2024"
    copyright = false
    author = false
    rss = true
    #toptext = ["Paul Pfeister"]
    toptext = ["EC68 CB3A 2653 02B7"]
    #bottomtext = ["EC68 CB3A 2653 02B7"]

[params.logo]
    #logoMark = ">"
    logoText = "~/"
    logoCursorColor = "#03f8fc"
    logoCursorPathname = true

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[taxonomies]
    tag = "tags"
    category = "categories"
    series   = "series"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = ""
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "cve"
    name = "Disclosures"
    url = "/categories/disclosures/"
    weight = 3
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 4
